### ISSUE TITLE
Add flag to delete empty directories

### ISSUE THREAD

**Issue by sparkblaze** [rokett/Housekeeper#11]
Housekeeper should have an optional flag to remove empty subdirectories.

`housekeeper.exe --ext "log" --older-than 30 --path "c:\logs" --recursive --case-insensitive --remove-directories` 

should remove any subdirectories that are now empty, but leave c:\logs intact.

**Comment by rokett** [comment]
Good idea.....I've added this option.  Just needs to be tested in your scenario before merging.....it worked ok in testing.
